### ISSUE TITLE
PKGBUILD specifies python3.7 directories

### ISSUE THREAD

**Issue by orestiskapar** [ros-melodic-arch/ros-melodic-angles#1]
This package's PKGBUILD still specifies `python3.7` directories. `arch4edu` maintainer suggested in https://github.com/arch4edu/arch4edu/issues/63#issuecomment-604287027 to open an issue about it.

I know you've already tracked in https://github.com/ros-melodic-arch/ros-melodic-desktop-full/issues/8 all packages affected by the change, but, like https://github.com/ros-melodic-arch/ros-melodic-actionlib-msgs/issues/1, it's not that the build fails. It's that things fail to work together afterwards.

**Comment by jwhendy** [comment]
Indeed, we should fix this... the point of [ros-melodic-desktop-full#8](https://github.com/ros-melodic-arch/ros-melodic-desktop-full/issues/8) is that *every* PKGBUILD here has these paths. We will get to it, but we also didn't want to confuse "nice to fix" with "fixes that matter."

My point in [ros-melodic-actionlib-msgs#1](https://github.com/ros-melodic-arch/ros-melodic-actionlib-msgs/issues/1) is that these paths *don't matter.* Things fail to work afterward because arch4edu hasn't rebuild these binaries on `python3.8`.

Are we on the same page about this, or do you believe this issue will fix anything?

As a temporary workaround, have you just built this from AUR directly with the python3.7 paths in the PKGBUILD?

**Comment by jwhendy** [comment]
I commented at the arch4edu issue, showing that it's their bundle, not the PKGBUILD. I'm going to close this as while it's true we want to fix it, it's currently an irrelevant and harmless artifact. We'll clean this up at some point via a project or meta-issue in desktop-full since it applies to almost all packages here.

**Comment by orestiskapar** [comment]
> Are we on the same page about this, or do you believe this issue will fix anything? ...
> As a temporary workaround, have you just built this from AUR directly with the python3.7 paths in the PKGBUILD?

I know changing this will not fix the problem in arch4edu, it is as you say a "nice to fix". I have installed the package succesfully building with this same PKGBUILD from the AUR.
